New
justekoro/essence pull request #2
Opened 2022-07-06 10:59 UTC by Jokay03J

transformation du site en react app

-ajout de plusieurs type de recherche(par ville,code postal,département,code du département)
-on peut maintenant cherche les types de carburent en même temps
-prix triable du plus petit au plus grand
-ajout de plusieurs media query(mobile,tablette,ordinateurs,ordinateurs large,extra large(4K))

photo:
![image](https://user-images.githubusercontent.com/55850775/177535190-20d6925e-64c7-474f-a255-82a2ca0992a5.png)
![image](https://user-images.githubusercontent.com/55850775/177535250-dc12e020-55f9-4159-a216-16eba083fcd1.png)
![image](https://user-images.githubusercontent.com/55850775/177535325-f9a0e1b2-f63c-4384-bbf5-bb68cb25b954.png)
![image](https://user-images.githubusercontent.com/55850775/177535394-717c66e6-8af9-4b69-a716-42d9d3f2e74b.png)

2022-07-06 12:15 UTC, Jokay03J commented
@justekoro

2022-07-06 12:18 UTC, justekoro commented
hello, merci pour ton travail !
je check ça quand je rentre chez moi :)

2022-07-06 15:10 UTC, justekoro requested changes
globalement, c'est plutôt cool, mais quelques changements seraient à faire : 
* correction de certaines fautes d'orthographe (pourra être fait plus tard)
* s'assurer que les données ne sont pas vides (voir pourquoi au screenshot ci-dessous:)
![image](https://user-images.githubusercontent.com/35098503/177583314-f31ca77c-9863-4a31-aff7-5fc0a9ec291e.png)
* refaire le readme (je m'en occuperai)
* changer la taille des selectlist 
![image](https://user-images.githubusercontent.com/35098503/177583985-2e505a4f-7c50-4ada-9136-7042f3b6cc09.png)
* ne pas enforcer la casse (maj non obligatoires)
* un autofill pour le nom des villes ? (pourra être ajouté plus tard)

sinon c'est top ! merci beaucoup pour ton travail !

2022-07-07 12:20 UTC, Jokay03J commented
-changement de design pour mui(material design)
-vérification que les donnée ne sont pas vide
-plus besoins d'enfoncer la maj pour faire une recherche :tada: 
-autofill(WIP,c'est prévus)

![image](https://user-images.githubusercontent.com/55850775/177771168-45257786-88f9-4b6b-a9e5-765c4ebcc6bb.png)

2022-07-16 10:05 UTC, Jokay03J commented
@justekoro

2022-07-16 11:44 UTC, justekoro requested changes
vraiment cool, merci beaucoup !
derniers changements demandés avant d'envoyer ça en prod :)

+ si tu peux, ce serait cool de changer le format d'affichage de la date de dernière MÀJ par JJ/MM/DD
![image](https://user-images.githubusercontent.com/35098503/179353442-7873b0cb-8c28-44da-b920-148da3b32106.png)

merci encore pour tout ton taff !

2022-07-16 11:44 UTC, justekoro commented on api/index.js
> +app.listen(process.env.PORT, () => {
```suggestion
app.listen(process.env.PORT || 3002, () => {
```

2022-07-16 11:44 UTC, justekoro commented on src/App.js
> +          .get(`${process.env.REACT_APP_URL_API}/api`)
ça pourrait être cool de définir ça dans un fichier à part, genre src/refs.js plutôt que d'avoir à créer une variable d'environnement

2022-07-16 11:46 UTC, justekoro commented
ah et j'oubliais, est-ce que tu penses que tu pourrais faire en sorte que les résultats s'auto-update lors du changement de state ?
par exemple, je change la ville de Paris à camphin-en-pévèle et j'aimerais que les résultats s'affichent directement

2022-07-16 11:49 UTC, Jokay03J commented on src/App.js
> +          .get(`${process.env.REACT_APP_URL_API}/api`)
Ba en faite si je fais sa, ça seras moins personnalisable et moins configurable facilement

2022-07-16 12:03 UTC, justekoro commented on src/App.js
> +          .get(`${process.env.REACT_APP_URL_API}/api`)
okok

2022-07-16 12:07 UTC, Jokay03J commented
> ah et j'oubliais, est-ce que tu penses que tu pourrais faire en sorte que les résultats s'auto-update lors du changement de state ?
> par exemple, je change la ville de Paris à camphin-en-pévèle et j'aimerais que les résultats s'affichent directement

Oui c'est possible

2022-07-16 19:08 UTC, Jokay03J commented
@justekoro

2022-07-17 13:05 UTC, justekoro reviewed
dernière ligne droite, est-ce que tu peux faire en sorte que quand on change la ville ça refresh tout aussi ?

2022-07-17 13:06 UTC, Jokay03J commented
> dernière ligne droite, est-ce que tu peux faire en sorte que quand on change la ville ça refresh tout aussi ?

Je te fait sa se soir, tu pourras re-review ?

2022-07-17 13:11 UTC, justekoro commented
yep, pas de soucis ! ---- On dim., 17 juil. 2022 15:06:59 +0200  ***@***.***  wrote ----



dernière ligne droite, est-ce que tu peux faire en sorte que quand on change la ville ça refresh tout aussi ?



Je te fait sa se soir, tu pourras re-review ?



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-17 18:18 UTC, Jokay03J commented
@justekoro  c'est bon j'ai ajouter ce que tu ma demander

2022-07-17 18:32 UTC, justekoro approved these changes
j'ai pas testé mais je te fais confiance ! je ferai juste deux trois corrections de fautes d'orthographe avant de push, merci beaucoup pour ton aide !

2022-07-18 16:31 UTC, merged

2022-07-18 16:31 UTC, justekoro commented
merci encore pour ton travail !